/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Emergency.Emergencymanager;

import userinterface.Emergency.Emergencymanager.Manageambulancepanel;
import Business.Enterprise.Enterprise;
import Business.Organization.ECareManagerOganization;
import Business.UserAccount.UserAccount;
import Business.Ambulance.Ambulance;
import Business.Ambulance.Ambulancedirectory;
import static Logger.Logger.logger;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ksahi
 */
public class Ambulancedetpanel extends javax.swing.JPanel {

    /**
     * Creates new form Ambulancedetpanel
     */
    private JPanel userProcessContainer;
    private Ambulancedirectory ambulancelist;
    private Ambulance ambulance;

    public Ambulancedetpanel(JPanel userProcessContainer, Ambulancedirectory ambulancelist, Ambulance ambulance) {
         logger.log(Level.INFO, "Ambulancedetailspanel");

        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ambulancelist = ambulancelist;
        this.ambulance = ambulance;
        getDetails();
    }

    

    public void getDetails() {
        logger.log(Level.INFO, "getDetails --Ambulancedetailspanel");

        

        txtSerialNo.setText(ambulance.getSerialNo());
        txtVehicleNo.setText(ambulance.getAmbulanceNo());
        ComboBoxLocality.setSelectedItem(ambulance.getAvailableInArea());
        

        if (ambulance.isAvailability() == true) {
            btnYesVA.setSelected(true);
        } else {
            btnNoVA.setSelected(true);
        }

        txtVehicleNo.setEnabled(false);
        txtSerialNo.setEnabled(false);
        btnYesVA.setEnabled(false);
        btnNoVA.setEnabled(false);
        ComboBoxLocality.setEnabled(false);
        btnSave.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnNoVA = new javax.swing.JRadioButton();
        btnYesVA = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtVehicleNo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSerialNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ComboBoxLocality = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AMBULANCE DETAILS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 290, -1));

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setText(" Back");
        btnBack.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(110, 208, 202)));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 70, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Update Vehicle");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Vehicle Availability:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        buttonGroup1.add(btnNoVA);
        btnNoVA.setText("No");
        add(btnNoVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 50, -1));

        buttonGroup1.add(btnYesVA);
        btnYesVA.setText("Yes");
        add(btnYesVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 50, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Vehicle No:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        txtVehicleNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleNoActionPerformed(evt);
            }
        });
        add(txtVehicleNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 170, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Serial Number:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, 24));
        add(txtSerialNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 180, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Available Locality:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, 28));

        ComboBoxLocality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a locality", "Alphnosus Street", "Fenway", "Ruggles", "Rxbury Crossing", "Huntington Avenue", " " }));
        ComboBoxLocality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxLocalityActionPerformed(evt);
            }
        });
        add(ComboBoxLocality, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 180, -1));

        btnUpdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUpdate.setText("Update ");
        btnUpdate.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(110, 208, 202)));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 110, 30));

        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(110, 208, 202)));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 110, 30));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imaiges/medicare image 1.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setMaximumSize(new java.awt.Dimension(1500, 1000));
        jLabel6.setMinimumSize(new java.awt.Dimension(1500, 1000));
        jLabel6.setPreferredSize(new java.awt.Dimension(1500, 1000));
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtVehicleNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleNoActionPerformed

    private void ComboBoxLocalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxLocalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxLocalityActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "btnBackActionPerformed --Ambulancedetailspanel");


        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        Component[] comps = this.userProcessContainer.getComponents();
        for (Component comp : comps) {
            if (comp instanceof Manageambulancepanel) {
                Manageambulancepanel createP = (Manageambulancepanel) comp;
                createP.gettable();
            }
            layout.previous(userProcessContainer);
        }

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
       logger.log(Level.INFO, "btnSaveActionPerformed --Ambulancedetailspanel");

        if (ComboBoxLocality.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Please choose a locality");
        }
        String locality = String.valueOf(ComboBoxLocality.getSelectedItem());

        boolean ambulanceavailability;
       // boolean maintenanceCertificate;

        if (btnYesVA.isSelected()) {
            btnYesVA.setSelected(true);
            ambulanceavailability = true;

        } else {
            btnNoVA.setSelected(true);
            ambulanceavailability = false;

        }

        ambulance.setAvailability(ambulanceavailability);
        ambulance.setAvailableInArea(locality);

        JOptionPane.showMessageDialog(null, "The entered Ambulance details have been saved successfully!");

        btnUpdate.setEnabled(true);
        txtVehicleNo.setEnabled(false);
        
        txtSerialNo.setEnabled(false);
        btnYesVA.setEnabled(false);
        btnNoVA.setEnabled(false);
        
        ComboBoxLocality.setEnabled(false);
        btnSave.setEnabled(false);


    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "btnUpdateActionPerformed --Ambulancedetailspanel");

        btnUpdate.setEnabled(false);
        txtVehicleNo.setEnabled(false);
        txtSerialNo.setEnabled(false);
        btnYesVA.setEnabled(true);
        btnNoVA.setEnabled(true);
        ComboBoxLocality.setEnabled(true);
        btnSave.setEnabled(true);
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxLocality;
    private javax.swing.JButton btnBack;
    private javax.swing.JRadioButton btnNoVA;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JRadioButton btnYesVA;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtSerialNo;
    private javax.swing.JTextField txtVehicleNo;
    // End of variables declaration//GEN-END:variables
}
