/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestRequest;
import Business.WorkQueue.WorkRequest;
import static Logger.Logger.logger;
import java.awt.CardLayout;
import java.util.logging.Level;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.AdministrativeRole.CreatePatientJPanel;

/**
 *

 * @author Lokesh Balaji

 */
public class Doctorworkareapanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private DoctorOrganization organization;
    private Enterprise enterprise;
    private UserAccount useraccount;
    private EcoSystem ecosystem;

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public Doctorworkareapanel(JPanel userProcessContainer, UserAccount useraccount, DoctorOrganization organization, Enterprise enterprise, EcoSystem ecosystem) {
        logger.log(Level.INFO, "Doctorworkareapanel");

        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.useraccount = useraccount;
        this.ecosystem = ecosystem;
        valuelb.setText(enterprise.getOrganzationName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valuelb = new javax.swing.JLabel();
        appointmentbt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseLabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 127, 127, 30));

        valuelb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        valuelb.setText("<value>");
        add(valuelb, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 127, 158, 26));

        appointmentbt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        appointmentbt.setText("Appointments");
        appointmentbt.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(110, 208, 202)));
        appointmentbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appointmentbtActionPerformed(evt);
            }
        });
        add(appointmentbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 188, 120, 29));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imaiges/medicare image 1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1500, 1000));
        jLabel1.setMinimumSize(new java.awt.Dimension(1500, 1000));
        jLabel1.setPreferredSize(new java.awt.Dimension(1500, 1000));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void appointmentbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentbtActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "appointmentbtActionPerformed --Doctorworkareapanel");

        appointmentpanel appointmentpanel = new appointmentpanel(userProcessContainer,
                enterprise, useraccount, ecosystem);
        userProcessContainer.add("apppointmentJPanel", appointmentpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_appointmentbtActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appointmentbt;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel valuelb;
    // End of variables declaration//GEN-END:variables
}
