/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.CovidCare.CovidCareList;
import Business.CovidCare.CovidCareRequirementType;
import Business.Patients.Patient;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CCarerequestToCCarefromHospital;
import static Logger.Logger.logger;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author monishmm
 */
public class OrganreqPanel extends javax.swing.JPanel {

    /**
     * Creates new form OrganreqPanel
     */
    private JPanel userProcessContainer;
    private Patient pat;
    private Enterprise enterprise;
    private CovidCareList orgnlist;
    private EcoSystem ecosystem;
    private UserAccount useraccount;
    
    public OrganreqPanel(JPanel userProcessContainer, Patient pat, Enterprise enterprise,EcoSystem ecosystem,UserAccount useraccount) {
         logger.log(Level.INFO, "OrganreqPanel");
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.pat = pat;
        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
        this.useraccount = useraccount;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Organcombobox = new javax.swing.JComboBox<>();
        organtypelbl = new javax.swing.JLabel();
        backbt = new javax.swing.JButton();
        savebt = new javax.swing.JButton();
        reqUnitslbl = new javax.swing.JLabel();
        reqUnitscombobox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Organ Request to Organ Bank");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 23, 656, -1));

        Organcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Option", "RTPCR", "PLASMA", "Rapidtest", "Ventilator" }));
        Organcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrgancomboboxActionPerformed(evt);
            }
        });
        add(Organcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 140, -1, -1));

        organtypelbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        organtypelbl.setText("Organ Type :");
        add(organtypelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 144, -1, -1));

        backbt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backbt.setText("Back");
        backbt.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(110, 208, 202)));
        backbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtActionPerformed(evt);
            }
        });
        add(backbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 80, 29));

        savebt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        savebt.setText("Save");
        savebt.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(110, 208, 202)));
        savebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtActionPerformed(evt);
            }
        });
        add(savebt, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 235, 80, 29));

        reqUnitslbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        reqUnitslbl.setText("Required Units :");
        add(reqUnitslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 183, -1, -1));

        reqUnitscombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Option", "1", "2", "3", "4" }));
        add(reqUnitscombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 179, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imaiges/med2.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtActionPerformed
        // TODO add your handling code here:
            

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        appointmentpanel apl = (appointmentpanel) component;
        apl.getorganreq();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backbtActionPerformed

    private void savebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "savebtActionPerformed --OrganreqPanel");

     
        String selOrgan= String.valueOf(Organcombobox.getSelectedItem());
        String selReqUnits = String.valueOf(reqUnitscombobox.getSelectedItem());

         for (Network n : ecosystem.getNetworkList()) {
                for (Enterprise emp : n.getEnterprisedirectory().getEnterpriselist()) {
                    if (emp.getEnterprisetype() == Enterprise.EnterpriseType.CovidCare) 
                    {
                        CCarerequestToCCarefromHospital reqtoOB = new CCarerequestToCCarefromHospital();
                        if((Organcombobox.getSelectedIndex()==0)||reqUnitscombobox.getSelectedIndex() ==0)
                        {
                            JOptionPane.showMessageDialog(userProcessContainer, "Select all options!");
                            return;
                        }
                        else
                        {
                            reqtoOB.setRequestedUnits(Integer.parseInt(selReqUnits));
                        }
                        //System.out.println("OBReqUnits"+reqtoOB.getReqUnits());
                        reqtoOB.setTaskStatus("0");
                        reqtoOB.setPatient(pat);                        
                        //OrganType organtype = new CovidCareRequirementType(selOrgan);
                        reqtoOB.setCcareType(selOrgan);
                        reqtoOB.setSendEnterprise(this.enterprise);
                        emp.getWorkqueue().getWorkRequestAList().add(reqtoOB);
                       
                        useraccount.getWorkqueue().getWorkRequestAList().add(reqtoOB); 
                        savebt.setEnabled(false);
                        Organcombobox.setEnabled(false);
                        reqUnitscombobox.setEnabled(false);    
                    }
                }
            }
         JOptionPane.showMessageDialog(userProcessContainer, "Details sent to Organ Bank");
         
        return;
    }//GEN-LAST:event_savebtActionPerformed

    private void OrgancomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrgancomboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrgancomboboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Organcombobox;
    private javax.swing.JButton backbt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel organtypelbl;
    private javax.swing.JComboBox<String> reqUnitscombobox;
    private javax.swing.JLabel reqUnitslbl;
    private javax.swing.JButton savebt;
    // End of variables declaration//GEN-END:variables
}
