
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Validity.ValidateString;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Network.Network;
import static Logger.Logger.logger;
//import com.sun.org.apache.bcel.internal.classfile.InnerClass;
import java.awt.CardLayout;
import java.awt.Component;

import javax.swing.InputVerifier;

import java.util.logging.Level;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class Manageenterprisepanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    private EnterpriseDirectory enterprisedirectory;

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public Manageenterprisepanel(JPanel userProcessContainer, EcoSystem system) {
        logger.log(Level.INFO, "Manageenterprisepanel Started");

        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        jPanel1.setVisible(false);
        deletebt.setVisible(false);
        vlb.setVisible(false);
        gettable();
        getcombobox();

    }

    private void gettable() {
        logger.log(Level.INFO, "gettable --Manageenterprisepanel");

        DefaultTableModel mod = (DefaultTableModel) enterprisetable.getModel();

        mod.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            for (Enterprise ent : network.getEnterprisedirectory().getEnterpriselist()) {
                Object[] row = new Object[4];
                row[0] = ent;
                row[1] = network.getName();
                row[2] = ent.getEnterprisetype().getValue();
                try {
                    if (ent.getEmailid() == null || ent.getEmailid().isEmpty()) {
                        row[3] = "No MailID added";
                    } else {
                        row[3] = ent.getEmailid();
                    }
                } catch (NullPointerException e) {
                    row[3] = "No MailID added";
                }

                mod.addRow(row);
            }
        }
    }

    private void getcombobox() {
       logger.log(Level.INFO, "getcombobox --Manageenterprisepanel");
        networkJComboBox.removeAllItems();
        enterpriseTypeJComboBox.removeAllItems();

        for (Network network : system.getNetworkList()) {
            networkJComboBox.addItem(network);
        }

        for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()) {
            enterpriseTypeJComboBox.addItem(type);
        }

    }

    private void addInputVerifiers() {
        InputVerifier stringValidation = new ValidateString();
        nametxt.setInputVerifier(stringValidation);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backbt = new javax.swing.JButton();
        deletebt = new javax.swing.JButton();
        vlb = new javax.swing.JLabel();
        manageEnt = new javax.swing.JLabel();
        submitbt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        networkJComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        enterpriseTypeJComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mailtxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enterprisetable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1000, 585));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backbt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backbt.setText("Back");
        backbt.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(110, 208, 202)));
        backbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtActionPerformed(evt);
            }
        });
        add(backbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 80, 29));

        deletebt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        deletebt.setText("Delete");
        deletebt.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(110, 208, 202)));
        deletebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtActionPerformed(evt);
            }
        });
        add(deletebt, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 610, 80, 29));

        vlb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        vlb.setText("View Enterprise");
        add(vlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 130, -1));

        manageEnt.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        manageEnt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageEnt.setText("MANAGER ENTERPRISE");
        add(manageEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1010, -1));

        submitbt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        submitbt.setText("Submit");
        submitbt.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(110, 208, 202)));
        submitbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtActionPerformed(evt);
            }
        });
        add(submitbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 80, 29));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Network:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        networkJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(networkJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 190, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Enterprise Type:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        enterpriseTypeJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(enterpriseTypeJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 190, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));
        add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 190, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Mail ID:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        mailtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailtxtActionPerformed(evt);
            }
        });
        add(mailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 190, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Add Enterprise");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 130, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("View");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(110, 208, 202)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 80, 29));

        enterprisetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ENTERPRISE NAME", "NETWORK", "TYPE", "MAIL ID"
            }
        ));
        jScrollPane1.setViewportView(enterprisetable);
        if (enterprisetable.getColumnModel().getColumnCount() > 0) {
            enterprisetable.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel1.add(jScrollPane1);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 490, 160));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imaiges/medicare image 1.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        jLabel5.setMaximumSize(new java.awt.Dimension(1500, 1000));
        jLabel5.setMinimumSize(new java.awt.Dimension(1500, 1000));
        jLabel5.setPreferredSize(new java.awt.Dimension(1500, 1000));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 920, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void submitbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtActionPerformed
        logger.log(Level.INFO, "submitbtActionPerformed --Manageenterprisepanel");
        jPanel1.setVisible(true);
        deletebt.setVisible(true);
        vlb.setVisible(true);
        if (nametxt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter valid name !");
            return;
        }

        Network net = (Network) networkJComboBox.getSelectedItem();
        Enterprise.EnterpriseType type = (Enterprise.EnterpriseType) enterpriseTypeJComboBox.getSelectedItem();

        if (net == null || type == null) {
            JOptionPane.showMessageDialog(null, "Invalid Input!");
            return;
        }

        String name = nametxt.getText();

        for (Enterprise e : net.getEnterprisedirectory().getEnterpriselist()) {
            if (name.equalsIgnoreCase(e.getOrganzationName())) {
                JOptionPane.showMessageDialog(null, "Enterprise exits!");
                return;
            }
        }

        String mailID = mailtxt.getText();

        if (!mailID.isEmpty()) {
            Pattern VALID_EMAIL_ADDRESS_REGEX
                    = Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);
            Matcher matcher = VALID_EMAIL_ADDRESS_REGEX.matcher(mailID);

            if (!matcher.matches()) {
                JOptionPane.showMessageDialog(userProcessContainer, "Please enter email ID");
                return;
            }
        }

        Enterprise enterprise = net.getEnterprisedirectory().CreateEnterprise(name, type, mailID);

        for (Enterprise e
                : net.getEnterprisedirectory()
                        .getEnterpriselist()) {
            if (name.equalsIgnoreCase(e.getEmailid())) {
                JOptionPane.showMessageDialog(null, "MailID already exits!");
                return;
            }
        }

        JOptionPane.showMessageDialog(null, "Enterprise has been added successfully");
        gettable();

        nametxt.setText(
                "");
        mailtxt.setText(
                "");
        networkJComboBox.setSelectedIndex(
                0);
        enterpriseTypeJComboBox.setSelectedIndex(
                0);

    }//GEN-LAST:event_submitbtActionPerformed

    private void backbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtActionPerformed
        
        logger.log(Level.INFO, "backbtActionPerformed --Manageenterprisepanel");
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        Systemadminworkareapanel sysAdminwjp = (Systemadminworkareapanel) component;
        sysAdminwjp.gettree();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backbtActionPerformed

    private void deletebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "deletebtActionPerformed --Manageenterprisepanel");
        int selectedrow = enterprisetable.getSelectedRow();
        if (selectedrow >= 0) {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to delete the enterprise?");
            if (dialogResult == JOptionPane.YES_OPTION) {
                Enterprise enterprise = (Enterprise) enterprisetable.getValueAt(selectedrow, 0);
                for (Network network : system.getNetworkList()) {
                    this.enterprisedirectory = network.getEnterprisedirectory();
                }
                enterprisedirectory.deleteenterprise(enterprise);
                JOptionPane.showMessageDialog(null, "Deleted successfully");
                gettable();
            }

        } else {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }

    }//GEN-LAST:event_deletebtActionPerformed

    private void mailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailtxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       jPanel1.setVisible(true);
       deletebt.setVisible(true);
       vlb.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    public void resetFields() {
        nametxt.setText("");
        mailtxt.setText("");
        networkJComboBox.setSelectedIndex(0);
        enterpriseTypeJComboBox.setSelectedIndex(0);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbt;
    private javax.swing.JButton deletebt;
    private javax.swing.JComboBox enterpriseTypeJComboBox;
    private javax.swing.JTable enterprisetable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mailtxt;
    private javax.swing.JLabel manageEnt;
    private javax.swing.JTextField nametxt;
    private javax.swing.JComboBox networkJComboBox;
    private javax.swing.JButton submitbt;
    private javax.swing.JLabel vlb;
    // End of variables declaration//GEN-END:variables
}
