/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.Enterprise.Enterprise;
import Business.Patients.Patient;
import static Logger.Logger.logger;
//import Mail.SendMail;
//import javax.mail.MessagingException;
import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author monishmm
 */
public class Createpatientpanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;

    private Enterprise enterprise;

    /**
     * Creates new form CreatePatient
     */
    Createpatientpanel(JPanel userProcessContainer, Enterprise enterprise) {
       logger.log(Level.INFO, "CreatePatientJPanel");

        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        savebt = new javax.swing.JButton();
        backbt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bloodcombobox = new javax.swing.JComboBox<>();
        lblPatientName = new javax.swing.JLabel();
        patientnametxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        patientHRNtxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        savebt.setText("Save");
        savebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtActionPerformed(evt);
            }
        });
        add(savebt, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, -1, -1));

        backbt.setText("Back");
        backbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtActionPerformed(evt);
            }
        });
        add(backbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Add Patient");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jLabel2.setText("Blood Group");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        bloodcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Blood Group", "O+", "O-", "B+", "B-", "AB+", "AB-", "A+", "A-" }));
        add(bloodcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, -1, -1));

        lblPatientName.setText("Patient Name");
        add(lblPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));
        add(patientnametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 412, -1));

        jLabel1.setText("Patient HRN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));
        add(patientHRNtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 165, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void savebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtActionPerformed
        // TODO add your handling code here:  
        logger.log(Level.INFO, "btnPatientSubmitActionPerformed --createpatient");

        String patHRN = patientHRNtxt.getText();

        if (patientnametxt.getText().length() == 0) {
            JOptionPane.showMessageDialog(userProcessContainer, "Enter Name");
            return;
        }
        if (patHRN.length() == 0) {
            JOptionPane.showMessageDialog(userProcessContainer, "Enter HRN");
            return;
        }
        for (Patient pat : enterprise.getPatientdirectory().getPatientList()) {
            if (pat.getPatientHRN().equals(patHRN)) {
                JOptionPane.showMessageDialog(userProcessContainer, "HRN already exist");
                return;
            }
        }
        if (patientnametxt.getText().matches(".*\\d.*")) {
            JOptionPane.showMessageDialog(userProcessContainer, "Only enter alphabets");
            return;
        }

        if (bloodcombobox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(userProcessContainer, "Please select a blood group");
            return;
        }
        Patient patient = enterprise.getPatientdirectory().addPatient();
        patient.setPatientName(patientnametxt.getText());
        patient.setPatientHRN(patHRN);
        patient.setBloodGroup(bloodcombobox.getSelectedItem().toString());
        JOptionPane.showMessageDialog(userProcessContainer, "Patient Sucessfully Created");      

        patientHRNtxt.setText("");
        patientnametxt.setText("");
        bloodcombobox.setSelectedIndex(0);
    }//GEN-LAST:event_savebtActionPerformed

    private void backbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "btnPatientSubmitActionPerformed --createpatient");

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backbtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbt;
    private javax.swing.JComboBox<String> bloodcombobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JTextField patientHRNtxt;
    private javax.swing.JTextField patientnametxt;
    private javax.swing.JButton savebt;
    // End of variables declaration//GEN-END:variables
}
