/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Location.Location;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Patients.Patient;
import Business.WorkQueue.MsgfromNurseToHospWorkRequest;
import Business.WorkQueue.TransportWorkRequest;
import Business.WorkQueue.WorkRequest;
import static Logger.Logger.logger;
//import Mail.SendMail;
//import javax.mail.MessagingException;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author monishmm
 */
public class TransferReqpanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;

    /**
     * Creates new form TransferRequest
     */
    public TransferReqpanel(JPanel userProcessContainer, Enterprise enterprise) {
        logger.log(Level.INFO, "TransferRequest");
        initComponents();
        this.enterprise = enterprise;
        this.userProcessContainer = userProcessContainer;
        gettable();
        getcombobox();

    }

    public void gettable() {
        logger.log(Level.INFO, "populateTable --TransferRequest");

        DefaultTableModel mod = (DefaultTableModel) reqtable.getModel();
        mod.setRowCount(0);
        if (enterprise.getWorkqueue().getWorkrequestlist().size() > 0) {
            for (WorkRequest workreq : enterprise.getWorkqueue().getWorkrequestlist()) {
                if (workreq.getClass().getName().contains("TransportWorkRequest")) {
                    if (((TransportWorkRequest) workreq).isIstransfer()) {
                        Object row[] = new Object[1];
                        row[0] = ((TransportWorkRequest) workreq).getTransferpatient();
                        mod.addRow(row);
                    }
                }
            }
        }
    }

    public void getcombobox() {
        logger.log(Level.INFO, "populateComboBox --IncomingRequest");

        OrganizationDirectory org = enterprise.getOrganizationdirectory();

        for (Organization o : org.getOrglist()) {
            if (o.getName().equals("Doctor Organization")) {
                for (Employee u : o.getEmployeedirectory().getEmployeelist()) {
                    doctorcombobox.addItem(u.toString());
                }
            }
        }
        for (Location loc : enterprise.getLocationlist().getLocationlist()) {
            lcationcombobox.addItem(loc.getLocationname());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        reqtable = new javax.swing.JTable();
        admitbt = new javax.swing.JButton();
        backbt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pathrntxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        doctorcombobox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lcationcombobox = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reqtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient"
            }
        ));
        jScrollPane1.setViewportView(reqtable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 85, -1, 186));

        admitbt.setText("Admit");
        admitbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admitbtActionPerformed(evt);
            }
        });
        add(admitbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 14, -1, -1));

        backbt.setText("Back");
        backbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtActionPerformed(evt);
            }
        });
        add(backbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel1.setText("Patient HRN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));
        add(pathrntxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 152, -1));

        jLabel2.setText("Doctor");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        doctorcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Doctor" }));
        add(doctorcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, -1, -1));

        jLabel3.setText("Location");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, -1));

        lcationcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Location" }));
        add(lcationcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void admitbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admitbtActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "jButton1ActionPerformed --IncomingRequest");

        if (doctorcombobox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(userProcessContainer, "Please Select a Doctor");
            return;
        }
        if (lcationcombobox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(userProcessContainer, "Please select a Location");
            return;
        }
        if (pathrntxt.getText().length() == 0) {
            JOptionPane.showMessageDialog(userProcessContainer, "Please enter HRN");
            return;
        }
        for (Patient patient : enterprise.getPatientdirectory().getPatientList()) {
            if (patient.getPatientHRN().equals(pathrntxt.getText())) {
                JOptionPane.showMessageDialog(userProcessContainer, "HRN already exist");
                return;
            }
        }
        int selectedRow = reqtable.getSelectedRow();
        if (selectedRow >= 0) {
            Patient pat = (Patient) reqtable.getValueAt(selectedRow, 0);
            String emp = doctorcombobox.getSelectedItem().toString();
            ArrayList<Organization> org = enterprise.getOrganizationdirectory().getOrglist();
            for (Organization o : org) {
            if (o.getName().equals("Doctor Organization")) {
            for (Employee e : o.getEmployeedirectory().getEmployeelist()) {
            if (e.getEmpname().equals(emp)) {
            String location = lcationcombobox.getSelectedItem().toString();
            for (Location locat : enterprise.getLocationlist().getLocationlist()) {
          if (locat.getLocationname().equals(location)) {
             if (locat.getNurselist().size() == 0) {
             JOptionPane.showMessageDialog(userProcessContainer, "Currently nurse is not available in this location");
                       return;
                                    }
            if (locat.getMaximum() >= (locat.getCount() + 1)) {
             Patient newPatient = enterprise.getPatientdirectory().addPatient();
              newPatient.setDoctor(e);
               newPatient.setLocation(locat);
               newPatient.setPatientName(pat.getPatientName());
                newPatient.setPatientHRN(pathrntxt.getText());
               newPatient.setAllergies(pat.getAllergies());
                  newPatient.setBloodGroup(pat.getBloodGroup());
                 newPatient.setMedList(pat.getMedList());
                locat.setCount(locat.getCount() + 1);
                  JOptionPane.showMessageDialog(userProcessContainer, "In patient Admitted");

                    for (WorkRequest workreq : enterprise.getWorkqueue().getWorkrequestlist()) {
                       if (workreq.getClass().getName().contains("TransportWorkRequest")) {
                       if (((TransportWorkRequest) workreq).getTransferpatient().getPatientName().
                          equals(pat.getPatientName())) {
                          enterprise.getWorkqueue().getWorkrequestlist().remove(workreq);
                         break;
                                                }
                       }
                    }
//                         
                 gettable();
                 return;
                 } else {
                 JOptionPane.showMessageDialog(userProcessContainer, locat.getLocationname()+ " is already full");
                                 
                 return;
                                    }
          }
            }
            }
            }
            }
            }

        } else {
            JOptionPane.showMessageDialog(userProcessContainer, "Please select a patient");
            return;
        }

    }//GEN-LAST:event_admitbtActionPerformed

    private void backbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backbtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admitbt;
    private javax.swing.JButton backbt;
    private javax.swing.JComboBox<String> doctorcombobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> lcationcombobox;
    private javax.swing.JTextField pathrntxt;
    private javax.swing.JTable reqtable;
    // End of variables declaration//GEN-END:variables
}
