/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.Common.ValidateStrings;
import Business.Employee.Employee;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import static Logger.Logger.logger;
import java.awt.CardLayout;

import javax.swing.InputVerifier;

import java.util.logging.Level;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author monishmm
 */
public class Manageemployeepanel extends javax.swing.JPanel {

    private OrganizationDirectory orgdir;
    private JPanel userProcessContainer;

    /**
     * Creates new form ManageOrganizationJPanel
     */
    public Manageemployeepanel(JPanel userProcessContainer, OrganizationDirectory orgdir) {
        logger.log(Level.INFO, "ManageEmployeeJPanel");

        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.orgdir = orgdir;

        addInputVerifiers();
        getorgcombobox();
        getorgempcombobox();
    }
         private void addInputVerifiers() {
        InputVerifier stringValidation = new ValidateStrings();
        nametxt.setInputVerifier(stringValidation);
        
        
    }
    public void getorgcombobox(){
        vieworgcombo.removeAllItems();

        for (Organization organization : orgdir.getOrglist()) {
            vieworgcombo.addItem(organization);
        }
    }

    public void getorgempcombobox() {
        logger.log(Level.INFO, "populateOrganizationEmpComboBox --ManageEmployeeJPanel");

        orgcmbobox.removeAllItems();

        for (Organization organization : orgdir.getOrglist()) {
            orgcmbobox.addItem(organization);
        }
    }

    private void gettable(Organization organization) {
        logger.log(Level.INFO, "populateTable --ManageEmployeeJPanel");

        DefaultTableModel mod = (DefaultTableModel) orgtable.getModel();

        mod.setRowCount(0);

        for (Employee emp : organization.getEmployeedirectory().getEmployeelist()) {
            Object[] row = new Object[2];
            row[0] = emp.getEmpid();
            row[1] = emp.getEmpname();
            mod.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orgtable = new javax.swing.JTable();
        vieworgcombo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        backbt = new javax.swing.JButton();
        manageEnt = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        submitbt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        orgcmbobox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orgtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orgtable);
        if (orgtable.getColumnModel().getColumnCount() > 0) {
            orgtable.getColumnModel().getColumn(0).setResizable(false);
            orgtable.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 380, 160));

        vieworgcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        vieworgcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vieworgcomboActionPerformed(evt);
            }
        });
        add(vieworgcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 200, -1));

        jLabel1.setText("Organization");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, -1, -1));

        backbt.setText("Back");
        backbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtActionPerformed(evt);
            }
        });
        add(backbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, -1, -1));

        manageEnt.setFont(new java.awt.Font("Tamil MN", 1, 18)); // NOI18N
        manageEnt.setText("MANAGE ORGANIZATION EMPLOYEE");
        add(manageEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tamil Sangam MN", 1, 18)); // NOI18N
        jLabel5.setText("View Organization Employee");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        submitbt.setText("Submit");
        submitbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtActionPerformed(evt);
            }
        });
        add(submitbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, -1, -1));

        jLabel3.setText("Organization");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        orgcmbobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(orgcmbobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 202, -1));

        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));
        add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 202, -1));

        jLabel4.setFont(new java.awt.Font("Tamil Sangam MN", 1, 18)); // NOI18N
        jLabel4.setText("Create Employee");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void submitbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtActionPerformed

        
        if(nametxt.getText().trim().isEmpty() || orgcmbobox.getSelectedIndex()<0)
        {
         JOptionPane.showMessageDialog(null, "Please provide input in all the fields");
         return;    
        }
        

        logger.log(Level.INFO, "addJButtonActionPerformed --ManageEmployeeJPanel");


        Organization org = (Organization) orgcmbobox.getSelectedItem();
        String name = nametxt.getText();

        org.getEmployeedirectory().createEmployee(name);
        JOptionPane.showMessageDialog(null, "Employee has been created successfully", "success",JOptionPane.PLAIN_MESSAGE);
        resetFields();
        gettable(org);
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Name field cannot be empty!!", "warning", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_submitbtActionPerformed

    private void backbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtActionPerformed

        logger.log(Level.INFO, "backJButtonActionPerformed --ManageEmployeeJPanel");

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backbtActionPerformed

    private void vieworgcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vieworgcomboActionPerformed
        logger.log(Level.INFO, "organizationJComboBoxActionPerformed --ManageEmployeeJPanel");

        Organization organization = (Organization) vieworgcombo.getSelectedItem();
        if (organization != null) {
            gettable(organization);
        }
    }//GEN-LAST:event_vieworgcomboActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel manageEnt;
    private javax.swing.JTextField nametxt;
    private javax.swing.JComboBox orgcmbobox;
    private javax.swing.JTable orgtable;
    private javax.swing.JButton submitbt;
    private javax.swing.JComboBox vieworgcombo;
    // End of variables declaration//GEN-END:variables

    private void resetFields() {
        nametxt.setText("");
        orgcmbobox.setSelectedIndex(0);
    }
}
