/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.Common.ValidatePasswords;
import Business.Common.ValidateStrings;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Roles.Role;
import Business.UserAccount.Useraccount;
import static Logger.Logger.logger;
import java.awt.CardLayout;
import java.util.logging.Level;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author monishmm
 */
public class ManageUserAccpanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageUserAccpanel
     */
    private JPanel container;
    private Enterprise enterprise;
    private Useraccount useraccount;

    public ManageUserAccpanel(JPanel container, Enterprise enterprise, Useraccount useraccount) {
         initComponents();
        this.container = container;
        this.enterprise = enterprise;
        this.useraccount = useraccount;
       
      
        addInputVerifiers();
        getorganizationcombo();
        
        getdata();
    }



    public void getorganizationcombo() {
        logger.log(Level.INFO, "popOrganizationComboBox --ManageUserAccountJPanel");

        orgcmbobox.removeAllItems();

        for (Organization org : enterprise.getOrganizationdirectory().getOrglist()) {
            orgcmbobox.addItem(org);
        }
    }

    public void getEmployeeComboBox(Organization organization) {
        logger.log(Level.INFO, "populateEmployeeComboBox --ManageUserAccountJPanel");

        empcombobox.removeAllItems();

        for (Employee emp : organization.getEmployeedirectory().getEmployeelist()) {
            empcombobox.addItem(emp);
        }
    }

    private void getrolecombobox(Organization organization) {
        logger.log(Level.INFO, "populateRoleComboBox --ManageUserAccountJPanel");

        rolecmbobox.removeAllItems();
        for (Role role : organization.getSupportedRole()) {
            rolecmbobox.addItem(role);
        }
    }

    private void addInputVerifiers() {
        logger.log(Level.INFO, "addInputVerifiers --ManageUserAccountJPanel");

        InputVerifier stringValidation = new ValidateStrings();
        usernametxt.setInputVerifier(stringValidation);
        InputVerifier passwordValidation = new ValidatePasswords();
        passwordtxt.setInputVerifier(passwordValidation);
    }

    public void getdata() {
        logger.log(Level.INFO, "popData --ManageUserAccountJPanel");

        DefaultTableModel mod = (DefaultTableModel) userTable.getModel();

        mod.setRowCount(0);

        for (Organization organization : enterprise.getOrganizationdirectory().getOrglist()) {
            for (Useraccount ua : organization.getUseraccountdirectory().getUseraccountlist()) {
                Object row[] = new Object[2];
                row[0] = ua;
                row[1] = ua.getRole();
                ((DefaultTableModel) userTable.getModel()).addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        backbt = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        manageEnt = new javax.swing.JLabel();
        submitbt = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        orgcmbobox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        empcombobox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        rolecmbobox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        usernametxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passwordtxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(userTable);
        if (userTable.getColumnModel().getColumnCount() > 0) {
            userTable.getColumnModel().getColumn(0).setResizable(false);
            userTable.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 410, 190));

        backbt.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        backbt.setText("Back");
        backbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtActionPerformed(evt);
            }
        });
        add(backbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, 88, -1));

        jLabel7.setFont(new java.awt.Font("Tamil Sangam MN", 1, 18)); // NOI18N
        jLabel7.setText("View User Accounts");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, -1, -1));

        manageEnt.setFont(new java.awt.Font("Tamil MN", 1, 18)); // NOI18N
        manageEnt.setText("MANAGE USER ACCOUNT");
        add(manageEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        submitbt.setText("Submit");
        submitbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtActionPerformed(evt);
            }
        });
        add(submitbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, -1, -1));

        jLabel5.setText("Organization");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        orgcmbobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        orgcmbobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgcmboboxActionPerformed(evt);
            }
        });
        add(orgcmbobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 146, -1));

        jLabel3.setText("Employee");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        empcombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(empcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 146, -1));

        jLabel4.setText("Role");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        rolecmbobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(rolecmbobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 146, -1));

        jLabel1.setText("User Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));
        add(usernametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 290, 146, -1));

        jLabel2.setText("Password");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));
        add(passwordtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 146, -1));

        jLabel8.setFont(new java.awt.Font("Tamil Sangam MN", 1, 18)); // NOI18N
        jLabel8.setText("Create User Account");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    private void submitbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtActionPerformed
        try
        {
        String username = usernametxt.getText();
        String passWord = passwordtxt.getText();
        Organization organization = (Organization) orgcmbobox.getSelectedItem();
        if(username.isEmpty() || passWord.isEmpty())
            {
            JOptionPane.showMessageDialog(null, "Please provide inputs!", "warning", JOptionPane.WARNING_MESSAGE);  
            return;
            }
        
        for(Useraccount ua : organization.getUseraccountdirectory().getUseraccountlist()){
            if(username.equalsIgnoreCase(ua.getUsername())){
            JOptionPane.showMessageDialog(null, "User Name already exists!!", "warning", JOptionPane.WARNING_MESSAGE);  
            return;
            }
        }
        
        
        Employee employee = (Employee) empcombobox.getSelectedItem();
        Role role = (Role) rolecmbobox.getSelectedItem();

        Useraccount userAccount = organization.getUseraccountdirectory().createAccount(username, passWord, employee, role);
        userAccount.setNetwork((Network)useraccount.getNetwork());
        userAccount.setEnabled(true);
        getdata();
        JOptionPane.showMessageDialog(null, " User Account has been created successfully", "success",JOptionPane.PLAIN_MESSAGE);
        resetFields();
        }
        catch(Exception e)
       {
        JOptionPane.showMessageDialog(this, "Please enter valid data", "warning",JOptionPane.WARNING_MESSAGE);    
       }
    }//GEN-LAST:event_submitbtActionPerformed


    private void backbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "backjButton1ActionPerformed --ManageUserAccountJPanel");

        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backbtActionPerformed

    private void orgcmboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgcmboboxActionPerformed
        logger.log(Level.INFO, "organizationJComboBoxActionPerformed --ManageUserAccountJPanel");

        Organization organization = (Organization) orgcmbobox.getSelectedItem();
        if (organization != null) {
            getEmployeeComboBox(organization);
            getrolecombobox(organization);
        }
    }//GEN-LAST:event_orgcmboboxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbt;
    private javax.swing.JComboBox empcombobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel manageEnt;
    private javax.swing.JComboBox orgcmbobox;
    private javax.swing.JTextField passwordtxt;
    private javax.swing.JComboBox rolecmbobox;
    private javax.swing.JButton submitbt;
    private javax.swing.JTable userTable;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables

    private void resetFields() {
        usernametxt.setText("");
        passwordtxt.setText("");
        orgcmbobox.setSelectedIndex(0);
        empcombobox.setSelectedIndex(0);
        rolecmbobox.setSelectedIndex(0);
    }
}
