/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.Enterprise.Enterprise;

import Business.Enterprise.EnterpriseDirectory;

import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.Organization.OrganizationDirectory;
import static Logger.Logger.logger;
import java.awt.CardLayout;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author monishmm
 */
public class ManageOrganizationpanel extends javax.swing.JPanel {

    private Enterprise enterprise;
    private JPanel userProcessContainer;
    private Organization organization;

    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageOrganizationpanel(JPanel userProcessContainer, Enterprise directory) {
        logger.log(Level.INFO, "ManageOrganizationJPanel");

        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = directory;

        gettable();
        getcombo();
    }

    private void getcombo() {
        logger.log(Level.INFO, "populateCombo --ManageOrganizationJPanel");

        orgcombobox.removeAllItems();

        if (enterprise.getEnterprisetype() == Enterprise.EnterpriseType.EmergencyCare) {
            for (Type type : Organization.Type.values()) {
                if (type.getValue().equals(Type.EmergencycareManager.getValue()) || type.getValue().equals(Type.Driver.getValue())
                        || type.getValue().equals(Type.EmergencycareNurse.getValue())) {
                    orgcombobox.addItem(type);
                }
            }
        } else if (enterprise.getEnterprisetype() == Enterprise.EnterpriseType.BloodBank) {
            for (Type type : Organization.Type.values()) {
               if (type.getValue().equals(Type.Manager.getValue()) || type.getValue().equals(Type.Clinicians.getValue())
                    || type.getValue().equals(Type.Lab.getValue())) {
                    orgcombobox.addItem(type);
                }
            }

        } else if (enterprise.getEnterprisetype() == Enterprise.EnterpriseType.Hospital) {
            for (Type type : Organization.Type.values()) {
                if (type.getValue().equals(Type.Doctor.getValue()) || type.getValue().equals(Type.Nurse.getValue())) {
                    orgcombobox.addItem(type);
                }

            }
        }

    }

    private void gettable() {

        DefaultTableModel mod = (DefaultTableModel) orgtable.getModel();

        mod.setRowCount(0);

        for (Organization organization : enterprise.getOrganizationdirectory().getOrglist()) {
            Object[] row = new Object[2];
            row[0] = organization.getOrganizationid();
            row[1] = organization;
            mod.addRow(row);
        }
    }
   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        orgtable = new javax.swing.JTable();
        backbt = new javax.swing.JButton();
        manageEnt = new javax.swing.JLabel();
        delbt = new javax.swing.JButton();
        submitbt = new javax.swing.JButton();
        viewrglb = new javax.swing.JLabel();
        orglb = new javax.swing.JLabel();
        orgcombobox = new javax.swing.JComboBox();
        addorglb = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orgtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orgtable);
        if (orgtable.getColumnModel().getColumnCount() > 0) {
            orgtable.getColumnModel().getColumn(0).setResizable(false);
            orgtable.getColumnModel().getColumn(1).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 370, 140));

        backbt.setText("Back");
        backbt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtActionPerformed(evt);
            }
        });
        add(backbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, -1, -1));

        manageEnt.setFont(new java.awt.Font("Tamil MN", 1, 18)); // NOI18N
        manageEnt.setText("MANAGE ORGANIZATION");
        add(manageEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        delbt.setText("Delete");
        delbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbtActionPerformed(evt);
            }
        });
        add(delbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 530, -1, -1));

        submitbt.setText("Submit");
        submitbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtActionPerformed(evt);
            }
        });
        add(submitbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, -1, -1));

        viewrglb.setFont(new java.awt.Font("Tamil Sangam MN", 1, 18)); // NOI18N
        viewrglb.setText("View Organization");
        add(viewrglb, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, -1));

        orglb.setText("Organization Type ");
        add(orglb, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        orgcombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        orgcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgcomboboxActionPerformed(evt);
            }
        });
        add(orgcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 153, -1));

        addorglb.setFont(new java.awt.Font("Tamil Sangam MN", 1, 18)); // NOI18N
        addorglb.setText("Add an Organization");
        add(addorglb, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void submitbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtActionPerformed

        Type type = (Type) orgcombobox.getSelectedItem();

        if(type == null)
        {
       //JOptionPane.showMessageDialog(this, "Please select a organization!", "warning",JOptionPane.PLAIN_MESSAGE);
            JOptionPane.showMessageDialog(this, "Please select a organization!");
        return;     
        }
        
        for (Organization org : enterprise.getOrganizationdirectory().getOrglist()) {
            if (type.getValue().equals(org.getName())) {
                JOptionPane.showMessageDialog(null, "The organization already exists!", "warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        enterprise.getOrganizationdirectory().createOrganization(type);
        gettable();
    }//GEN-LAST:event_submitbtActionPerformed

    private void backbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtActionPerformed
        logger.log(Level.INFO, "backJButtonActionPerformed --ManageOrganizationJPanel");

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backbtActionPerformed

    private void orgcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgcomboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orgcomboboxActionPerformed

    private void delbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbtActionPerformed

        int selectedRow = orgtable.getSelectedRow();
        if(selectedRow >= 0)
        {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Would you like to delete the row ", "warning",dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION)
            {

                Organization org = (Organization)orgtable.getValueAt(selectedRow, 1);
                enterprise.getOrganizationdirectory().removeorganization(org);
            }
            gettable();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please select a row", "warning",JOptionPane.PLAIN_MESSAGE);
        }

    }//GEN-LAST:event_delbtActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addorglb;
    private javax.swing.JButton backbt;
    private javax.swing.JButton delbt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel manageEnt;
    private javax.swing.JComboBox orgcombobox;
    private javax.swing.JLabel orglb;
    private javax.swing.JTable orgtable;
    private javax.swing.JButton submitbt;
    private javax.swing.JLabel viewrglb;
    // End of variables declaration//GEN-END:variables
}
