/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Bloodbank;

import Business.Blood.Bloodgroup;
import Business.Blood.Bloodgrouplist;
import Business.Enterprise.Enterprise;
import Business.Organization.Clinicianorganization;
import Business.UserAccount.Useraccount;
import static Logger.Logger.logger;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.util.HashSet;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.EMS.EMSNurse.EMSNurseWorkAreaJPanel;
import userinterface.LabAssistantRole.LabAssistantWorkAreaJPanel;

/**
 *
 * @author Lokesh Balaji
 */
public class Createbloodgrppanel extends javax.swing.JPanel {

    /**
     * Creates new form Createbloodgrppanel
     */
    private JPanel userProcessContainer;
    private Clinicianorganization organization;
    private Enterprise enterprise;
    private Useraccount useraccount;
    private Bloodgroup bloodgrp;
    private Bloodgrouplist Bloodgrplist;

    public Createbloodgrppanel(JPanel userProcessContainer, Bloodgroup bloodgrp, Bloodgrouplist Bloodgrplist) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.bloodgrp = bloodgrp;
        this.organization = organization;
        this.Bloodgrplist = Bloodgrplist;
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backbt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bgtxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        AUtxt = new javax.swing.JTextField();
        savebt = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backbt.setText("Back");
        backbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtActionPerformed(evt);
            }
        });
        add(backbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tamil MN", 1, 18)); // NOI18N
        jLabel4.setText("CREATE BLOOD DETAILS");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jLabel2.setText("Blood Group :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));
        add(bgtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 83, -1));

        jLabel3.setText("Available Units :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, -1, -1));

        AUtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AUtxtActionPerformed(evt);
            }
        });
        AUtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AUtxtKeyTyped(evt);
            }
        });
        add(AUtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 83, -1));

        savebt.setText("Save");
        savebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtActionPerformed(evt);
            }
        });
        add(savebt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void AUtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AUtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AUtxtActionPerformed

    private void savebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "btnSaveActionPerformed --createBloodGroupJPanel");

        String bloodgrp = bgtxt.getText();
        String availunits = AUtxt.getText();

        if (bloodgrp.equals("") || bloodgrp.isEmpty() || availunits.equals("") || availunits.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter values for all the fields");
            return;
        }
        if (Bloodgrplist.getBloodgrplist().size() > 0) {
            for (Bloodgroup bg : Bloodgrplist.getBloodgrplist()) {
                if (bloodgrp.equalsIgnoreCase(String.valueOf(bg))) {
                    JOptionPane.showMessageDialog(null, "BloodGroup already exists");
                    bgtxt.setText("");
                    AUtxt.setText("");
                    return;
                }
            }
        }
        this.bloodgrp = new Bloodgroup(bloodgrp, availunits);
        Bloodgrplist.addBG(this.bloodgrp);
        JOptionPane.showMessageDialog(null, "BloodGroup details added successfully");
        bgtxt.setText("");
        AUtxt.setText("");
        return;
    }//GEN-LAST:event_savebtActionPerformed

    private void backbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "jButton1ActionPerformed --createBloodGroupJPanel");

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        Clinicianworkareapanel dwjp = (Clinicianworkareapanel) component;
        dwjp.gettable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backbtActionPerformed

    private void AUtxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AUtxtKeyTyped
        // TODO add your handling code here:
        char vchar = evt.getKeyChar();
        if (!(Character.isDigit(vchar))
                || (vchar == KeyEvent.VK_BACK_SPACE)
                || (vchar == KeyEvent.VK_DELETE)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Please enter a number");
        }
    }//GEN-LAST:event_AUtxtKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AUtxt;
    private javax.swing.JButton backbt;
    private javax.swing.JTextField bgtxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton savebt;
    // End of variables declaration//GEN-END:variables
}
