/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CovidCare;

import Business.BloodGroup.BloodGroup;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.CovidCare.CovidCareList;
import Business.CovidCare.CovidCareRequirementType;
import Business.Organization.CCarePhysicianOrganization;
import Business.UserAccount.UserAccount;
import static Logger.Logger.logger;
import java.awt.CardLayout;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ksahi
 */
public class CovidPhysicianWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form CovidPhysicianWorkArea
     */
    
    private JPanel userProcessContainer;
    private CCarePhysicianOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem ecosystem;
    private CovidCareRequirementType covidcaretype;
    private CovidCareList covidcarelist;
    
    
    
    
    public CovidPhysicianWorkArea(JPanel userProcessContainer,  UserAccount userAccount,CCarePhysicianOrganization organization, Enterprise enterprise, EcoSystem ecosystem) {
        
        logger.log(Level.INFO, "OBClinicianWorkArea");
        
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.ecosystem = ecosystem;
        this.covidcarelist = enterprise.getCCareList();
        this.covidcaretype = covidcaretype;
        gettable();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        OverallCovidTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnUpdateBloodUnits = new javax.swing.JButton();
        btnEMSReq = new javax.swing.JButton();
        btnHosReq = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OverallCovidTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Covid Care Requirement", "AVAILABLE UNITS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(OverallCovidTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 105, 383, 222));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("COVID PHYSICIAN WORK AREA");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 780, -1));

        btnCreate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCreate.setText("New Requirement Type");
        btnCreate.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(110, 208, 202)));
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 356, 149, 29));

        btnRefresh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(110, 208, 202)));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 413, 140, 29));

        btnUpdateBloodUnits.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUpdateBloodUnits.setText("Update covid care requirement Units");
        btnUpdateBloodUnits.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(110, 208, 202)));
        btnUpdateBloodUnits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBloodUnitsActionPerformed(evt);
            }
        });
        add(btnUpdateBloodUnits, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 356, 230, 29));

        btnEMSReq.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnEMSReq.setText("View Emergency Requests");
        btnEMSReq.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(110, 208, 202)));
        btnEMSReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEMSReqActionPerformed(evt);
            }
        });
        add(btnEMSReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 215, 261, 29));

        btnHosReq.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnHosReq.setText("View Hospital Requests");
        btnHosReq.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(110, 208, 202)));
        btnHosReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHosReqActionPerformed(evt);
            }
        });
        add(btnHosReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 132, 261, 29));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imaiges/medicare image 1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1500, 1000));
        jLabel1.setMinimumSize(new java.awt.Dimension(1500, 1000));
        jLabel1.setPreferredSize(new java.awt.Dimension(1500, 1000));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "btnCreateActionPerformed --OBClinicianWorkArea");

        CreateCovidReqTypePanel panel = new CreateCovidReqTypePanel(userProcessContainer, covidcaretype, covidcarelist);
        userProcessContainer.add("CreatecovidcarereqTypePanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "btnRefreshActionPerformed --OBClinicianWorkArea");

        gettable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnUpdateBloodUnitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBloodUnitsActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "btnUpdateBloodUnitsActionPerformed --OBClinicianWorkArea");

        int selectedrow = OverallCovidTable.getSelectedRow();

        if (selectedrow >= 0) {
            
            CovidCareRequirementType ot = (CovidCareRequirementType) OverallCovidTable.getValueAt(selectedrow, 0);
            UpdateCovidtypeJPanel panel = new UpdateCovidtypeJPanel(userProcessContainer, ot, covidcarelist,enterprise,userAccount);
            userProcessContainer.add("CreateJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select a row"); }

    }//GEN-LAST:event_btnUpdateBloodUnitsActionPerformed

    private void btnEMSReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEMSReqActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "btnEMSReqActionPerformed --OBClinicianWorkArea");

        CovidEmergencyReqPanel panel = new CovidEmergencyReqPanel(userProcessContainer, covidcaretype, covidcarelist, enterprise, userAccount, ecosystem);
        userProcessContainer.add("OBEmergencyReqPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnEMSReqActionPerformed

    private void btnHosReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHosReqActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "btnEMSReqActionPerformed --OBClinicianWorkArea");
        
        
        CovidHosReqPanel panel = new CovidHosReqPanel(userProcessContainer, covidcaretype, covidcarelist, enterprise, userAccount, ecosystem);
        userProcessContainer.add("OBHosReqPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
        
        
        
        
    }//GEN-LAST:event_btnHosReqActionPerformed

    void gettable() {
        logger.log(Level.INFO, "gettable --OBClinicianWorkArea");

        DefaultTableModel dtm = (DefaultTableModel) OverallCovidTable.getModel();
        dtm.setRowCount(0);

         //for (BloodGroup bloodgroup : bloodgrouplist.getBloodgrplist())
             
        for (CovidCareRequirementType ot : covidcarelist.getCCareTypeAList()) {

            Object row[] = new Object[2];
            row[0] = ot;
            row[1] = ot.getAvailUnits();
            //row[1] = bloodgroup.getAvailableunits();
            
            dtm.addRow(row);
        }
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable OverallCovidTable;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnEMSReq;
    private javax.swing.JButton btnHosReq;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdateBloodUnits;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
