/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Bloodbank;

import Business.Blood.Bloodgroup;
import Business.Blood.Bloodgrouplist;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Clinicianorganization;
import Business.Organization.Doctororganization;
import Business.Organization.Laborganization;
import Business.Organization.Managerorganization;
import Business.Organization.Organization;
import Business.Roles.LabAssistantRole;
import Business.UserAccount.Useraccount;
import Business.WorkQueue.BloodReqToNewBB;
import Business.WorkQueue.BloodrequestToBBfromEMS;
import Business.WorkQueue.BloodrequestToBBfromHospital;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import static Logger.Logger.logger;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;
import java.util.Map.Entry;
import java.util.logging.Level;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author Lokesh Balaji
 */
public class Managerroleworkareapanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagerRoleWorkArea
     */
    private JPanel userProcessContainer;
    private Managerorganization organization;
    private Enterprise enterprise;
    private Useraccount userAccount;
    private Clinicianorganization co;
    private List<Entry<String, Integer>> topBloodUnits;
    private List<Entry<String, Integer>> topRequests;
    private Bloodgroup bloodgroup;
    private Bloodgrouplist bloodgrouplist;
    private EcoSystem ecosystem;

    public Managerroleworkareapanel(JPanel userProcessContainer, Useraccount account, Managerorganization organization, Enterprise enterprise, EcoSystem ecosystem) {
        logger.log(Level.INFO, "ManagerRoleWorkAreaJPanel");

        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        valueLabel.setText(enterprise.getName());

        this.ecosystem = ecosystem;
        //populateRequestTable();
        //populatePieChartData();
        populateTextFields();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        top3ReqBlood = new javax.swing.JButton();
        manageEnt2 = new javax.swing.JLabel();
        pieChartPanel = new javax.swing.JPanel();
        totalHelpReq = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        manageEnt1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        TotHspReq = new javax.swing.JTextField();

        top3ReqBlood.setText("View top 3 Requested Blood Groups");
        top3ReqBlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                top3ReqBloodActionPerformed(evt);
            }
        });

        manageEnt2.setFont(new java.awt.Font("Tamil MN", 1, 13)); // NOI18N
        manageEnt2.setText("Enterprise:");

        pieChartPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalHelpReq.setText("Total No of  Requests  ");

        valueLabel.setFont(new java.awt.Font("Tamil MN", 1, 13)); // NOI18N
        valueLabel.setText("<value>");

        manageEnt1.setFont(new java.awt.Font("Tamil MN", 1, 18)); // NOI18N
        manageEnt1.setText("MANAGER WORK AREA");

        jButton1.setText("Top 3 Requested Blood units");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Top 3 Blood Requests");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 333, Short.MAX_VALUE)
                .addComponent(manageEnt2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(464, 464, 464))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(totalHelpReq)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TotHspReq, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(55, 55, 55)
                        .addComponent(pieChartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(manageEnt1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalHelpReq)
                            .addComponent(TotHspReq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(manageEnt1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(valueLabel)
                            .addComponent(manageEnt2))
                        .addGap(55, 55, 55)
                        .addComponent(pieChartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(402, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
//
    private void top3ReqBloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_top3ReqBloodActionPerformed

    }//GEN-LAST:event_top3ReqBloodActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "jButton1ActionPerformed --ManagerRoleWorkAreaJPanel");

        //findTop3BloodRequest();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         logger.log(Level.INFO, "jButton2ActionPerformed --ManagerRoleWorkAreaJPanel");
            //findTop3();
            
                                               
    }                                        
                                                    
    
      public void populateTextFields()
      {
         
          logger.log(Level.INFO, "PopulateTextFields --ManagerRoleWorkAreaJPanel");
          int totalReq = 0;
         
          try
          {
  
           for(Network network : ecosystem.getNetworkList()){
               if(enterprise.equals(this.enterprise)){
                  totalReq = enterprise.getWorkqueue().getWorkrequestlist().size(); 
           for(Organization org: enterprise.getOrganizationdirectory().getOrglist()){
               if(org instanceof Clinicianorganization){
                   totalReq  = totalReq + org.getWorkqueue().getWorkrequestlist().size();
               }
               if(org instanceof Laborganization){
                   totalReq  = totalReq + org.getWorkqueue().getWorkrequestlist().size();
               }
                   
           }
           }
           
          
          // TotHspReq.setText(String.valueOf(totalHospReq));
           }
           TotHspReq.setText(String.valueOf(totalReq));
           TotHspReq.setEnabled(false);

          }
          catch (Exception e)
          {
              JOptionPane.showMessageDialog(null, "No Data to display");
          }

       
        

    }//GEN-LAST:event_jButton2ActionPerformed

 

//
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TotHspReq;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel manageEnt1;
    private javax.swing.JLabel manageEnt2;
    private javax.swing.JPanel pieChartPanel;
    private javax.swing.JButton top3ReqBlood;
    private javax.swing.JLabel totalHelpReq;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
