/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.Validity.ValidatePassword;
import Business.Validity.ValidateString;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Roles.Role;
import Business.UserAccount.UserAccount;
import static Logger.Logger.logger;
import java.awt.CardLayout;
import java.util.logging.Level;
import javax.swing.InputVerifier;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author monishmm
 */
public class ManageUserAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageUserAccountJPanel
     */
    private JPanel container;
    private Enterprise enterprise;
    private UserAccount useraccount;

    public ManageUserAccountJPanel(JPanel container, Enterprise enterprise, UserAccount useraccount) {
         
        logger.log(Level.INFO, "ManageUserAccpanel");
        
        initComponents();
        this.container = container;
        this.enterprise = enterprise;
        this.useraccount = useraccount;
       jPanel1.setVisible(false);
       vlb.setVisible(false);
      
        addInputVerifiers();
        getorganizationcombo();
        
        getdata();
    }



    public void getorganizationcombo() {
        logger.log(Level.INFO, "getorganizationcombo --ManageUserAccpanel");

        orgcmbobox.removeAllItems();

        for (Organization org : enterprise.getOrganizationdirectory().getOrganizationAList()) {
            orgcmbobox.addItem(org);
        }
    }

    public void getEmployeeComboBox(Organization organization) {
         logger.log(Level.INFO, "getEmployeeComboBox --ManageUserAccpanel");

        empcombobox.removeAllItems();

        for (Employee emp : organization.getEmployeedirectory().getEmployeeAList()) {
            empcombobox.addItem(emp);
        }
    }

    private void getrolecombobox(Organization organization) {
        logger.log(Level.INFO, "getrolecombobox --ManageUserAccpanel");

        rolecmbobox.removeAllItems();
        for (Role role : organization.getSupportedRole()) {
            rolecmbobox.addItem(role);
        }
    }

    private void addInputVerifiers() {
        logger.log(Level.INFO, "addInputVerifiers --ManageUserAccpanel");

        InputVerifier stringValidation = new ValidateString();
        usernametxt.setInputVerifier(stringValidation);
        InputVerifier passwordValidation = new ValidatePassword();
        passwordtxt.setInputVerifier(passwordValidation);
    }

    public void getdata() {
        logger.log(Level.INFO, "getdata --ManageUserAccpanel");

        DefaultTableModel mod = (DefaultTableModel) userTable.getModel();

        mod.setRowCount(0);

        for (Organization organization : enterprise.getOrganizationdirectory().getOrganizationAList()) {
            for (UserAccount ua : organization.getUseraccountdirectory().getUseraccountlist()) {
                Object row[] = new Object[2];
                row[0] = ua;
                row[1] = ua.getRole();
                ((DefaultTableModel) userTable.getModel()).addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backbt = new javax.swing.JButton();
        vlb = new javax.swing.JLabel();
        manageEnt = new javax.swing.JLabel();
        submitbt = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        orgcmbobox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        empcombobox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        rolecmbobox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        usernametxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        passwordtxt = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backbt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backbt.setText("Back");
        backbt.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(110, 208, 202)));
        backbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtActionPerformed(evt);
            }
        });
        add(backbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 80, 29));

        vlb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        vlb.setText("View User Accounts");
        add(vlb, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, -1));

        manageEnt.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        manageEnt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageEnt.setText("MANAGE USER ACCOUNT");
        add(manageEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 980, -1));

        submitbt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        submitbt.setText("Submit");
        submitbt.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(110, 208, 202)));
        submitbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbtActionPerformed(evt);
            }
        });
        add(submitbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 80, 29));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Organization:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        orgcmbobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        orgcmbobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgcmboboxActionPerformed(evt);
            }
        });
        add(orgcmbobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 146, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Employee:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, -1, -1));

        empcombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(empcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 146, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Role:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        rolecmbobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(rolecmbobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 146, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Username:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));
        add(usernametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 146, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Password:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Create User Account");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("View");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(110, 208, 202)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 80, 29));

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(userTable);
        if (userTable.getColumnModel().getColumnCount() > 0) {
            userTable.getColumnModel().getColumn(0).setResizable(false);
            userTable.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.add(jScrollPane1);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 460, 220));
        add(passwordtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 150, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imaiges/medicare image 1.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setMaximumSize(new java.awt.Dimension(1500, 1000));
        jLabel7.setMinimumSize(new java.awt.Dimension(1500, 1000));
        jLabel7.setPreferredSize(new java.awt.Dimension(1500, 1000));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 950));
    }// </editor-fold>//GEN-END:initComponents


    private void submitbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbtActionPerformed
        
         logger.log(Level.INFO, "submitbtActionPerformed --ManageUserAccpanel");
        
        jPanel1.setVisible(true);
        vlb.setVisible(true);
        
        try
        {
        String username = usernametxt.getText();
        String passWord = passwordtxt.getText();
        Organization organization = (Organization) orgcmbobox.getSelectedItem();
        if(username.isEmpty() || passWord.isEmpty())
            {
            JOptionPane.showMessageDialog(null, "Please provide inputs!", "warning", JOptionPane.WARNING_MESSAGE);  
            return;
            }
        
        for(UserAccount ua : organization.getUseraccountdirectory().getUseraccountlist()){
            if(username.equalsIgnoreCase(ua.getUsername())){
            JOptionPane.showMessageDialog(null, "User Name already exists!!", "warning", JOptionPane.WARNING_MESSAGE);  
            return;
            }
        }
        
        
        Employee employee = (Employee) empcombobox.getSelectedItem();
        Role role = (Role) rolecmbobox.getSelectedItem();

        UserAccount userAccount = organization.getUseraccountdirectory().createAccount(username, passWord, employee, role);
        userAccount.setNetwork((Network)useraccount.getNetwork());
        userAccount.setEnabled(true);
        getdata();
        JOptionPane.showMessageDialog(null, " User Account has been created successfully", "success",JOptionPane.PLAIN_MESSAGE);
        resetFields();
        }
        catch(Exception e)
       {
        JOptionPane.showMessageDialog(this, "Please enter valid data", "warning",JOptionPane.WARNING_MESSAGE);    
       }
    }//GEN-LAST:event_submitbtActionPerformed


    private void backbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "backbtActionPerformed --ManageUserAccpanel");

        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_backbtActionPerformed

    private void orgcmboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgcmboboxActionPerformed
        logger.log(Level.INFO, "orgcmboboxActionPerformed --ManageUserAccpanel");

        Organization organization = (Organization) orgcmbobox.getSelectedItem();
        if (organization != null) {
            getEmployeeComboBox(organization);
            getrolecombobox(organization);
        }
    }//GEN-LAST:event_orgcmboboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPanel1.setVisible(true);
        vlb.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbt;
    private javax.swing.JComboBox empcombobox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel manageEnt;
    private javax.swing.JComboBox orgcmbobox;
    private javax.swing.JPasswordField passwordtxt;
    private javax.swing.JComboBox rolecmbobox;
    private javax.swing.JButton submitbt;
    private javax.swing.JTable userTable;
    private javax.swing.JTextField usernametxt;
    private javax.swing.JLabel vlb;
    // End of variables declaration//GEN-END:variables

    private void resetFields() {
        usernametxt.setText("");
        passwordtxt.setText("");
        orgcmbobox.setSelectedIndex(0);
        empcombobox.setSelectedIndex(0);
        rolecmbobox.setSelectedIndex(0);
    }
}
