/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userinterface.BloodBank;

import Business.BloodGroup.BloodGroup;
import Business.BloodGroup.Bloodgrouplist;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.PhysicianOrganization;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BloodReqToNewBloodBank;
import Business.WorkQueue.WorkRequest;
import static Logger.Logger.logger;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lokesh Balaji
 */
public class Clinicianworkreqpanel extends javax.swing.JPanel {

    /**
     * Creates new form Clinicianworkreqpanel
     */
    private JPanel userProcessContainer;
    private PhysicianOrganization organization;
    private Enterprise enterprise;
    private UserAccount useraccount;
    private BloodGroup bloodgrp;
    private Bloodgrouplist bloodgrplist;
    private EcoSystem ecosystem;
    private Network network;
    private Enterprise.EnterpriseType enterprisetype;
    private OrganizationDirectory organizationdirectory;

    public Clinicianworkreqpanel(JPanel userProcessContainer, BloodGroup bloodgrp, Bloodgrouplist bloodgrplist, Enterprise enterprise, UserAccount useraccount, EcoSystem ecosystem) {
        logger.log(Level.INFO, "Clinicianworkreqpanel");

        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.bloodgrp = bloodgrp;
        this.bloodgrplist = bloodgrplist;
        this.network = network;
        this.ecosystem = ecosystem;
        this.useraccount = useraccount;
        this.enterprise = enterprise;
        this.enterprisetype = enterprisetype;
        this.organization = organization;
        this.organizationdirectory = organizationdirectory;

        getbloodreqtable();
        getreqitemstable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageEnt1 = new javax.swing.JLabel();
        manageEnt = new javax.swing.JLabel();
        assignbt = new javax.swing.JButton();
        backbt = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        bloodrequesttable = new javax.swing.JTable();
        acceptbt = new javax.swing.JButton();
        declinebt = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        reqtable = new javax.swing.JTable();
        manageEnt2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageEnt1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        manageEnt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageEnt1.setText("CLINICIAN REQUEST AREA");
        add(manageEnt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 770, -1));

        manageEnt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        manageEnt.setText("Blood Requests");
        add(manageEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 130, -1));

        assignbt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        assignbt.setText("Assign ");
        assignbt.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(110, 208, 202)));
        assignbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignbtActionPerformed(evt);
            }
        });
        add(assignbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 80, 29));

        backbt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        backbt.setText("Back");
        backbt.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(110, 208, 202)));
        backbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtActionPerformed(evt);
            }
        });
        add(backbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 80, 29));

        bloodrequesttable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BLOOD GROUP", "REQUESTOR", "NO OF UNITS", "REQUEST STATUS", "ASSIGNED TO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(bloodrequesttable);
        if (bloodrequesttable.getColumnModel().getColumnCount() > 0) {
            bloodrequesttable.getColumnModel().getColumn(0).setResizable(false);
            bloodrequesttable.getColumnModel().getColumn(1).setResizable(false);
            bloodrequesttable.getColumnModel().getColumn(2).setResizable(false);
            bloodrequesttable.getColumnModel().getColumn(3).setResizable(false);
            bloodrequesttable.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 750, 143));

        acceptbt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        acceptbt.setText("Accept");
        acceptbt.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(110, 208, 202)));
        acceptbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptbtActionPerformed(evt);
            }
        });
        add(acceptbt, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 80, 29));

        declinebt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        declinebt.setText("Decline");
        declinebt.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(110, 208, 202)));
        declinebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declinebtActionPerformed(evt);
            }
        });
        add(declinebt, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, 80, 29));

        reqtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BLOOD GROUP", "REQUESTOR", "NO OF UNITS", "REQUEST STATUS", "ASSIGNED TO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(reqtable);
        if (reqtable.getColumnModel().getColumnCount() > 0) {
            reqtable.getColumnModel().getColumn(0).setResizable(false);
            reqtable.getColumnModel().getColumn(1).setResizable(false);
            reqtable.getColumnModel().getColumn(2).setResizable(false);
            reqtable.getColumnModel().getColumn(3).setResizable(false);
        }

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 750, 143));

        manageEnt2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        manageEnt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageEnt2.setText("Requested Items");
        add(manageEnt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 196, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imaiges/medicare image 1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1500, 1000));
        jLabel1.setMinimumSize(new java.awt.Dimension(1500, 1000));
        jLabel1.setPreferredSize(new java.awt.Dimension(1500, 1000));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 970));
    }// </editor-fold>//GEN-END:initComponents

//    private void getbloodreqtable() {
//        //System.out.println("aaa");
//        logger.log(Level.INFO, "getbloodreqtable --Clinicianworkreqpanel");
//
//        DefaultTableModel mod = (DefaultTableModel) bloodrequesttable.getModel();
//
//        mod.setRowCount(0);
//
//        for (Network net : ecosystem.getNetworkList()) {
//            System.out.println("aaa");
//        for (Enterprise enterprise : net.getEnterprisedirectory().getEnterpriselist()) {
//            System.out.println("bbb");
//        if (enterprise.getEnterprisetype() == Enterprise.EnterpriseType.BloodBank && enterprise.getName().equals(this.enterprise.getName())) {
//            System.out.println("ccc");
//       for (Organization organization : enterprise.getOrganizationdirectory().getOrglist()) {
//           System.out.println("ddd");
//        for (WorkRequest req : enterprise.getWorkqueue().getWorkrequestlist()) {
//            System.out.println("eee");
//            System.out.println("kkk"+req);
//        if(req.equals("BloodReqToNewBloodBank")){
//            System.out.println("aaa111" +req.getClass().getName());
//          Object[] row = new Object[5];
//          row[0] = ((BloodReqToNewBloodBank) req);
//          row[1] = req.getSender().getEmpuser().getEmpname();
//          row[2] = ((BloodReqToNewBloodBank) req).getReqUnits();
//          row[3] = req.getStatus();
//            try {
//                row[4] = req.getReceiver().getEmpuser().getEmpname();
//               } catch (NullPointerException e) {
//
//                   row[4] = "No Assignee yet";
//                     }
//                mod.addRow(row);
//                 }
//                }
//                    }
//                }
//            }
//        }
//    }
    
    
    private void getbloodreqtable() {
        //System.out.println("aaa");
        logger.log(Level.INFO, "populateBloodReqTable --ClinicianWorkReq");

        DefaultTableModel mod = (DefaultTableModel) bloodrequesttable.getModel();

        mod.setRowCount(0);

        for (Network net : ecosystem.getNetworkList()) {
            //System.out.println("aaa");
        for (Enterprise enterprise : net.getEnterprisedirectory().getEnterpriselist()) {
//            System.out.println("bbb");
        if (enterprise.getEnterprisetype() == Enterprise.EnterpriseType.BloodBank && enterprise.getOrganzationName().equals(this.enterprise.getOrganzationName())) {
//            System.out.println("ccc");
       for (Organization organization : enterprise.getOrganizationdirectory().getOrganizationAList()) {
           if(organization instanceof PhysicianOrganization){
               
          
           //System.out.println("ddd");
        for (WorkRequest req : organization.getWorkqueue().getWorkRequestAList()) {
//            System.out.println("eee");
//            System.out.println("kkk"+req);
        if(req instanceof BloodReqToNewBloodBank){
            //System.out.println("aaa111" +req.getClass().getName());
          Object[] row = new Object[5];
          row[0] = ((BloodReqToNewBloodBank) req);
          row[1] = req.getIssuer().getEmployeeUser().getEmployeeName();
          row[2] = ((BloodReqToNewBloodBank) req).getRequestedUnits();
          row[3] = req.getTaskStatus();
            try {
                row[4] = req.getReceipient().getEmployeeUser().getEmployeeName();
               } catch (NullPointerException e) {

                   row[4] = "No Assignee yet";
                     }
                mod.addRow(row);
                 }
                }
                    }
                }
            }
        }
        }
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    private void getreqitemstable() {
        logger.log(Level.INFO, "getreqitemstable --Clinicianworkreqpanel");

        DefaultTableModel mod = (DefaultTableModel) reqtable.getModel();

        mod.setRowCount(0);

        for (WorkRequest ua : this.useraccount.getWorkqueue().getWorkRequestAList()) {
            if(ua.getClass().getName().contains("BloodReqToNewBB")){
            Object[] row = new Object[5];
            row[0] = ((BloodReqToNewBloodBank) ua);
            row[1] = ua.getIssuer().getEmployeeUser().getEmployeeName();
            row[2] = ((BloodReqToNewBloodBank) ua).getRequestedUnits();
            row[3] = ua.getTaskStatus();
            try {
                row[4] = ua.getReceipient().getEmployeeUser().getEmployeeName();
            } catch (NullPointerException e) {
                row[4] = "No Assignee Yet";
            }
            mod.addRow(row);
        }
        }

        getbloodreqtable();

    }

    private void assignbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignbtActionPerformed

        logger.log(Level.INFO, "assignbtActionPerformed --ClinicianWorkReq");

        int selectedRow = bloodrequesttable.getSelectedRow();
        int rowCount = bloodrequesttable.getSelectedRowCount();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (rowCount > 1) {
            JOptionPane.showMessageDialog(null, "Please select only one row", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        WorkRequest workreq = (WorkRequest) bloodrequesttable.getValueAt(selectedRow, 0);
//        if(workreq.getReceiver()!=null){
//        JOptionPane.showMessageDialog(null, "Request has been processed earlier","warning",JOptionPane.WARNING_MESSAGE);
//        return;
//        }

        if (workreq.getTaskStatus().equals("In Progress")) {
            JOptionPane.showMessageDialog(null, "The request is already in process", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (workreq.getTaskStatus().equals("Accepted and Completed") || workreq.getTaskStatus().equals("Declined")) {
            JOptionPane.showMessageDialog(null, "Request has been completed earlier", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if ((workreq).getTaskStatus().equals("Pending")) {
            (workreq).setReceipient(useraccount);
            (workreq).setTaskStatus(BloodReqToNewBloodBank.RequestINPROGRESS);

            getbloodreqtable();
            JOptionPane.showMessageDialog(null, "The request is now assigned to you! Kindly process it");
        }

    }//GEN-LAST:event_assignbtActionPerformed

    private void backbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtActionPerformed

        logger.log(Level.INFO, "backJButtonActionPerformed --ClinicianWorkReq");

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        Clinicianworkareapanel dwjp = (Clinicianworkareapanel) component;
        dwjp.gettable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backbtActionPerformed

    private void declinebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declinebtActionPerformed
        // TODO add your handling code here:

        logger.log(Level.INFO, "btnDeclineActionPerformed --ClinicianWorkReq");

        int selectedRow = bloodrequesttable.getSelectedRow();
        int rowCount = bloodrequesttable.getSelectedRowCount();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (rowCount > 1) {
            JOptionPane.showMessageDialog(null, "Please select only one row", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        WorkRequest workr = (WorkRequest) bloodrequesttable.getValueAt(selectedRow, 0);
        if (workr.getReceipient().equals(useraccount)) {
            if (workr.getTaskStatus().equals("Pending")) {
                JOptionPane.showMessageDialog(null, "The request has to be assigned first");
            } else if (workr.getTaskStatus().equals("Accepted and Completed") || workr.getTaskStatus().equals("Declined")) {
                JOptionPane.showMessageDialog(null, "The request has been processed earlier");
            } else {
                (workr).setReceipient(useraccount);
                (workr).setTaskStatus(BloodReqToNewBloodBank.RequestREJECT);
                getbloodreqtable();
                JOptionPane.showMessageDialog(null, "The request has been declined due to shortage of blood");

            }
        } else {
            JOptionPane.showMessageDialog(null, "The Request has to be processed by " + workr.getReceipient().getEmployeeUser().getEmployeeName());
        }
    }//GEN-LAST:event_declinebtActionPerformed

    private void acceptbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptbtActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "btnAcceptActionPerformed --ClinicianWorkReq");

        int selectedRow = bloodrequesttable.getSelectedRow();
        int rowCount = bloodrequesttable.getSelectedRowCount();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (rowCount > 1) {
            JOptionPane.showMessageDialog(null, "Please select only one row", "warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (rowCount == 1) {
            WorkRequest wq = (WorkRequest) bloodrequesttable.getValueAt(selectedRow, 0);

            if (wq.getTaskStatus().equals("Pending")) {
                JOptionPane.showMessageDialog(null, "The request has to be assigned first");
            } else if (wq.getTaskStatus().equals("Accepted and Completed") || wq.getTaskStatus().equals("Declined")) {
                JOptionPane.showMessageDialog(null, "The request has been processed earlier");
            } else {
                String reqbloodgrp = ((BloodReqToNewBloodBank) wq).getBloodGroup().getBloodGroup();
                int vailunits = Integer.parseInt(((BloodReqToNewBloodBank) wq).getBloodGroup().getAvailUnits());
                int borrowunits = Integer.parseInt(((BloodReqToNewBloodBank) wq).getRequestedUnits());
                for (BloodGroup bloodgrp : this.bloodgrplist.getBloodGroupAList()) {
                    if (bloodgrp.getBloodGroup().equals(reqbloodgrp)) {
                        if (Integer.parseInt(bloodgrp.getAvailUnits()) > borrowunits) {
                            String TotalUnits = String.valueOf(vailunits + borrowunits);
                            ((BloodReqToNewBloodBank) wq).getBloodGroup().setAvailUnits(TotalUnits);
                            bloodgrp.setAvailUnits(String.valueOf((Integer.parseInt(bloodgrp.getAvailUnits()) - borrowunits)));
                            JOptionPane.showMessageDialog(null, "Request has been accepted");
                            wq.setTaskStatus(BloodReqToNewBloodBank.RequestACCEPT);
                            getbloodreqtable();
                            break;
                        } else {
                            JOptionPane.showMessageDialog(null, "Available Blood Units are lesser than the requested units, Please Decline the Request");
                        }
                    }
                }
            }
        }

    }//GEN-LAST:event_acceptbtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptbt;
    private javax.swing.JButton assignbt;
    private javax.swing.JButton backbt;
    private javax.swing.JTable bloodrequesttable;
    private javax.swing.JButton declinebt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel manageEnt;
    private javax.swing.JLabel manageEnt1;
    private javax.swing.JLabel manageEnt2;
    private javax.swing.JTable reqtable;
    // End of variables declaration//GEN-END:variables

}
