/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Emergency.Emergencymanager;

import Business.Enterprise.Enterprise;
import Business.Organization.ECareManagerOganization;
import Business.UserAccount.UserAccount;
import Business.Ambulance.Ambulance;
import Business.Ambulance.Ambulancedirectory;
import static Logger.Logger.logger;
import com.sun.glass.events.KeyEvent;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author krish
 */
public class Createvehiclepanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private JPanel userProcessContainer;
    private ECareManagerOganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Ambulancedirectory ambulancedirectory;
    private Ambulance ambulance;

    public Createvehiclepanel(JPanel userProcessContainer, Ambulancedirectory ambulancedirectory, Ambulance ambulance) {
        logger.log(Level.INFO, "Createvehiclepanel");
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ambulancedirectory = ambulancedirectory;
        this.ambulance = ambulance;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnYesVA = new javax.swing.JRadioButton();
        btnNoVA = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtVehicleNo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSerialNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        localityComboBox = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREATE AMBULANCE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 980, -1));

        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(110, 208, 202)));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 100, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Vehicle Availability:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, 20));

        buttonGroup1.add(btnYesVA);
        btnYesVA.setText("Yes");
        btnYesVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYesVAActionPerformed(evt);
            }
        });
        add(btnYesVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        buttonGroup1.add(btnNoVA);
        btnNoVA.setText("No");
        add(btnNoVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Vehicle No:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        txtVehicleNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleNoActionPerformed(evt);
            }
        });
        add(txtVehicleNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 180, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Serial Number:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, 24));

        txtSerialNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSerialNoKeyTyped(evt);
            }
        });
        add(txtSerialNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 180, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Available Locality:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, 28));

        localityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose a locality", "Alphnosus Street", "Fenway", "Ruggles", "Rxbury Crossing", "Huntington Avenue" }));
        localityComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localityComboBoxActionPerformed(evt);
            }
        });
        add(localityComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 180, -1));

        btnSave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(110, 208, 202)));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 120, 40));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imaiges/medicare image 1.jpg"))); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(1500, 1000));
        jLabel5.setMinimumSize(new java.awt.Dimension(1500, 1000));
        jLabel5.setPreferredSize(new java.awt.Dimension(1500, 1000));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtVehicleNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleNoActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "btnSaveActionPerformed --Createvehiclepanel");

        String ambulancenumber = txtVehicleNo.getText();
        if (ambulancenumber == null || ambulancenumber.equals("")) {
            JOptionPane.showMessageDialog(null, "Vehicle Number cannot be empty");
            return;
        }
        for (Ambulance v : ambulancedirectory.getAmbulanceAList()) {
            if (ambulancenumber.equals(v.getAmbulanceNo())) {
                JOptionPane.showMessageDialog(null, "The Vehicle No already exists!", "warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        
        if (localityComboBox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Please choose a locality");
        }
        String locality = String.valueOf(localityComboBox.getSelectedItem());

        String serial_no = txtSerialNo.getText();
        if (serial_no == null || serial_no.equals("")) {
            JOptionPane.showMessageDialog(null, "Vehicle Number cannot be empty");
            return;
        }
        for (Ambulance v : ambulancedirectory.getAmbulanceAList()) {
            if (serial_no.equals(v.getSerialNo())) {
                JOptionPane.showMessageDialog(null, "The Serial No already exists!", "warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        

        if (!btnYesVA.isSelected() && !btnNoVA.isSelected()) {
            JOptionPane.showMessageDialog(null, "Please choose an option in Vehicle Availability");
            return;
        }

        boolean Ambulanceavailability = true;

        if (btnYesVA.isSelected()) {
            Ambulanceavailability = true;
        } else {
            Ambulanceavailability = false;
        }

        this.ambulance = new Ambulance(Ambulanceavailability, ambulancenumber, serial_no, locality);
        ambulancedirectory.addAmbulance(this.ambulance);
        JOptionPane.showMessageDialog(null, "The entered Vehicle details have been saved successfully!");

        txtVehicleNo.setText("");
        txtSerialNo.setText("");
        
        localityComboBox.setSelectedIndex(0);
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        logger.log(Level.INFO, "btnBackActionPerformed --Createvehiclepanel");

        userProcessContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        cardLayout.previous(userProcessContainer);
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        Component[] comps = this.userProcessContainer.getComponents();
        for (Component comp : comps) {
            if (comp instanceof Manageambulanceservicepanel) {
                Manageambulanceservicepanel createP = (Manageambulanceservicepanel) comp;
                createP.gettable();
            }
            layout.previous(userProcessContainer);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void localityComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localityComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localityComboBoxActionPerformed

    private void txtSerialNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerialNoKeyTyped
        // TODO add your handling code here:
       
        logger.log(Level.INFO, "txtSerialNoKeyTyped --Createvehiclepanel");

        char vchar = evt.getKeyChar();
        if (!(Character.isDigit(vchar))
                || (vchar == KeyEvent.VK_BACKSPACE)
                || (vchar == KeyEvent.VK_DELETE)) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Please enter a number");
        }
    }//GEN-LAST:event_txtSerialNoKeyTyped

    private void btnYesVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYesVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnYesVAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JRadioButton btnNoVA;
    private javax.swing.JButton btnSave;
    private javax.swing.JRadioButton btnYesVA;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> localityComboBox;
    private javax.swing.JTextField txtSerialNo;
    private javax.swing.JTextField txtVehicleNo;
    // End of variables declaration//GEN-END:variables
}
